# Generated by Django 5.1.3 on 2024-12-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
            ],
        ),
    ]
