# Generated by Django 5.1.3 on 2025-01-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicianModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('Phone_number', models.IntegerField()),
                ('Instrument_type', models.CharField(max_length=255)),
            ],
        ),
    ]
