# Generated by Django 5.1.3 on 2025-01-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_mymodel_date_field_mymodel_date_time_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='big_integer_field',
            field=models.BigIntegerField(default=False),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='boolean_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='duration_field',
            field=models.DurationField(default=False),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='file_field',
            field=models.FileField(default=False, upload_to='upload/'),
        ),
    ]
